# lan.conf
# A configuration file for lanserv or ipmi_sim to configure the various
# communication parameters for the device.

name "ipmisim1"
set_working_mc 0x20

startlan 1
    addr :: 623
    priv_limit admin

    allowed_auths_callback none md2 md5 straight
    allowed_auths_user     none md2 md5 straight
    allowed_auths_operator none md2 md5 straight
    allowed_auths_admin    none md2 md5 straight

    guid a123456789abcdefa123456789abcdef
    lan_config_program "./ipmi_sim_lancontrol eth0"
endlan

chassis_control "/etc/ipmi/ipmi_sim_chassiscontrol 0x20"

sol "/dev/ttyS1" 115200 nortscts

user 1 true ""        "test" user  10 none md2 md5 straight
user 2 true "ipmiusr" "test" admin 10 none md2 md5 straight
