# lan.conf
# A configuration file for lanserv or ipmi_sim to configure the various
# communication parameters for the device.

name "ipmisim1"
set_working_mc 0x20
  startlan 1
    addr :: 9001
    priv_limit admin
    allowed_auths_callback none md2 md5 straight
    allowed_auths_user none md2 md5 straight
    allowed_auths_operator none md2 md5 straight
    allowed_auths_admin none md2 md5 straight
    guid a123456789abcdefa123456789abcdef
    lan_config_program "./ipmi_sim_lancontrol eth1"
  endlan

  chassis_control "/etc/ipmi/ipmi_sim_chassiscontrol 0x20"

  sol "/dev/ttyS1" 115200 history=4000,backupfile=/etc/ipmi_sim/solhist1 historyfru=10
  startnow false
  user 1 true  ""        "test" user     10       none md2 md5 straight
  user 2 true  "ipmiusr" "test" admin    10       none md2 md5 straight
set_working_mc 0x30
  serial 15 localhost 9012 codec VM

  startcmd "qemu-system-x86_64 --enable-kvm -drive file=/opt/qemu/cge-complete-image-x86-generic-64-2.ext2,format=raw -nographic -kernel /opt/qemu/bzImage-2 -append 'root=/dev/sdb console=ttyS0,115200' -net nic,model=e1000,macaddr=52:54:00:12:34:59 -net user,hostfwd=tcp::5557-10.0.2.15:22 -chardev socket,id=ipmi0,host=localhost,port=9012,reconnect=10 -device ipmi-bmc-extern,id=bmc0,chardev=ipmi0 -device isa-ipmi-kcs,bmc=bmc0,irq=5 -serial mon:tcp::9013,server,telnet,nowait"

  sol "telnet:localhost:9013" 115200
  startnow false
