#!/bin/sh
# SSH daemon for NanoKVM BMC

[ -x /usr/bin/ssh-keygen ] || exit 0
[ -x /usr/sbin/sshd ] || exit 1

PID_FILE="/var/run/sshd.pid"

umask 077

startssh() {
    [ ! -f /etc/ssh/ssh_host_rsa_key ] && /usr/bin/ssh-keygen -A
    printf "Starting sshd: "
    start-stop-daemon -S -q -x /usr/sbin/sshd \
        && echo "OK" || echo "FAIL"
}

start() {
    if [ -e /etc/kvm/ssh_stop ]; then
        if [ -e /boot/start_ssh_once ]; then
            rm -f /boot/start_ssh_once
            startssh
        else
            echo "SSH disabled (/etc/kvm/ssh_stop exists)"
            exit 0
        fi
    else
        startssh
    fi
}

stop() {
    printf "Stopping sshd: "
    start-stop-daemon -K -q -p "$PID_FILE" -x /usr/sbin/sshd \
        && echo "OK" || echo "FAIL"
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart|reload) stop; start ;;
    permanent_on) rm -f /etc/kvm/ssh_stop; start ;;
    permanent_off) touch /etc/kvm/ssh_stop; stop ;;
    *)
        echo "Usage: $0 {start|stop|restart|permanent_on|permanent_off}"
        exit 1
        ;;
esac

exit 0
