#!/bin/sh

DAEMON="ipmi_sim"
PIDFILE="/var/run/$DAEMON.pid"
STATEDIR="/var/ipmi_sim"
LOGFILE="/var/log/$DAEMON.log"

case "$1" in
	start)
		printf "Starting IPMI Simulator: "
		if start-stop-daemon -S -b -p "$PIDFILE" -m -O "$LOGFILE" -x "/usr/bin/$DAEMON" -- -n -f /etc/ipmi/ipmisim1.emu -c /etc/ipmi/lan.conf -s "${STATEDIR}/ipmisim1"; then
			echo "OK"
		else
			echo "FAIL"
		fi
		;;
	stop)
		printf "Stopping IPMI Simulator: "
		if start-stop-daemon -K -q -p "$PIDFILE" -x "/usr/bin/$DAEMON"; then
			echo "OK"
		else
			echo "FAIL"
		fi
		;;
  status)
    printf "IPMI Simulator Status: "
    if start-stop-daemon -K -q -t -p "$PIDFILE" -x "/usr/bin/$DAEMON"; then
      echo "Running"
    else
      echo "Stopped"
    fi
    ;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
